function [TEBD_env,info] = TEBD_evolve_Trotter1_Ured(TEBD_env,M_mult,varargin)
%TEBD_EVOLVE_TROTTER1_URED Summary of this function goes here
%   Detailed explanation goes here
    parameters = struct();
    parameters.EPS = 10^(-16);
    parameters.NORMALIZE = true;
    parameters.NUMBER_OF_STEPS=1;
    parameters = parameter_updater(parameters,varargin);

    info = struct();
    info.truncerr = cell(1,length(TEBD_env.Ulist_red));
    info.M = zeros(1,length(TEBD_env.Ulist_red));
    for i=1:parameters.NUMBER_OF_STEPS
        for pos = 1:2:length(TEBD_env.Ulist_red)
            [TEBD_env.StateMPS.matrices{pos}, ...
             TEBD_env.StateMPS.schmidt_list{pos}, ...
             TEBD_env.StateMPS.matrices{mod(pos,TEBD_env.chain_length)+1}, ...
             info.truncerr{pos},...
             info.M(pos)] =        TEBD_step_Ured(TEBD_env.StateMPS.matrices{pos}, ...
                                                  TEBD_env.StateMPS.matrices{mod(pos,TEBD_env.chain_length)+1},...
                                                  TEBD_env.StateMPS.schmidt_list{mod(pos,TEBD_env.chain_length)+1},...
                                                  TEBD_env.Ulist_red{pos}, ...
                                                  M_mult, ...
                                                  'EPS', parameters.EPS,...
                                                  'NORMALIZE', parameters.NORMALIZE);
        end
        for pos = 2:2:length(TEBD_env.Ulist_red)
            [TEBD_env.StateMPS.matrices{pos}, ...
             TEBD_env.StateMPS.schmidt_list{pos}, ...
             TEBD_env.StateMPS.matrices{mod(pos,TEBD_env.chain_length)+1}, ...
             info.truncerr{pos},...
             info.M(pos)] =        TEBD_step_Ured(TEBD_env.StateMPS.matrices{pos}, ...
                                                  TEBD_env.StateMPS.matrices{mod(pos,TEBD_env.chain_length)+1},...
                                                  TEBD_env.StateMPS.schmidt_list{mod(pos,TEBD_env.chain_length)+1},...
                                                  TEBD_env.Ulist_red{pos}, ...
                                                  M_mult, ...
                                                  'EPS', parameters.EPS,...
                                                  'NORMALIZE', parameters.NORMALIZE);
        end
    end


end

